### ISSUE TITLE
On Bayes' Rule

### ISSUE THREAD

**Issue by xiangjjj** [thomwolf/Math-stuffs#1]
Hi Thomwolf,

I happen to come across your interesting derivations on the KL-divergence and would like to provide my humble opinion.

When we apply the Bayes' rule to replace the numerator in the log-likelihood, it is important to note that product is transformed to addition, i.e., `log P(AB) =  log P(A) + log P(B|A)`.

As a consequence, after x2 and z are taken out of the inner sum, we need to **add** the remaining terms according to the Bayes' rule. Furthermore, the last coefficient should be take expectation over the marginal probability P(x2), which yields the joint probability.

Once again, notice that the last coefficient was **added** to the first one, meaning the original equation (5) holds if we add the r.h.s. with a function of P. But **I got stuck here** as I am not able to reduce this function of P down to 0.

Nevertheless, this function of P is a constant given a dataset X, and it does not affect the minimization of the KL-divergence.

Sorry that I could not write down the equation here, and please let me know if you have any thoughts on this.

Thank you.
Xiang

**Comment by thomwolf** [comment]
Oh thanks !!
You are totally right, that was a stupid mistake.
Then every works just right.
I corrected the pdf with the final derivation.
